### ISSUE TITLE
Inference regression

### ISSUE THREAD

**Issue by jsen-** [brson/error-chain#68]
Hi, 

This used to work on v0.5.
```rust
#[macro_use]
extern crate error_chain;
error_chain! { }

fn main() {
    ::std::fs::create_dir_all("path/to/some/dir")
        .chain_err(|| "Unable to create some directory").unwrap();
}
```

But on v0.6.1 I'm receiving this inference error:
```rust
#[macro_use]
extern crate error_chain;
use error_chain::ResultExt;
error_chain! { }

fn main() {
    ::std::fs::create_dir_all("path/to/some/dir")
        .chain_err(|| "Unable to create some directory").unwrap();
}
```

```
Running "cargo build":
   Compiling experiments v0.1.0 (file:///D:/projects/rust/experiments)
error[E0284]: type annotations required: cannot resolve `<_ as error_chain::ChainedError>::ErrorKind == _`
 --> src\main.rs:8:10
  |
8 |         .chain_err(|| "Unable to create some directory").unwrap();
  |          ^^^^^^^^^

error: aborting due to previous error

error: Could not compile `experiments`.

To learn more, run the command again with --verbose.

"cargo build" completed with code 101
It took approximately 0.638 seconds
```
*edit*: same error on v0.6.0

**Comment by Yamakaky** [comment]
Yeah, I know. Since `ChainErr` was replaces by the crate-level https://docs.rs/error-chain/0.6.1/error_chain/trait.ResultExt.html, `chain_err` doesn't know which `ChainedError` it should return. Not sure what do to to fix that without re-adding `ChainErr`.
As a temporary fix, you can do
```rust
let res: Result<_> = result.chain_err(..);
res.unwrap();
```

**Comment by jsen-** [comment]
Unfortunately, the same occurs for example here:
```rust
#[macro_use]
extern crate error_chain;
use error_chain::ResultExt;
error_chain! { }

fn real_main() -> Result<()> {
    ::std::fs::create_dir_all("path/to/some/dir")
        .chain_err(|| "Unable to create some directory")?;
    // do some more stuff
    Ok(())
}

fn main() {
    real_main().unwrap();
}
```
My code is littered with such constructs 😟

**Comment by Yamakaky** [comment]
Similar issue [here](https://github.com/brson/error-chain/pull/62).

**Comment by Arnavion** [comment]
The `()` inference is probably https://github.com/rust-lang/rust/issues/37181

**Comment by brson** [comment]
This rings a bell and may have been part of the original motivation for having the trait be per crate.
